### ISSUE TITLE
Missing required config options for Synapse

### ISSUE THREAD

**Issue by Routhinator** [dacruz21/matrix-chart#21]
Hi,

Looks like we're missing an option to set a few things for synapse. 

I am unable to create admin users from the shell and I'm seeing this error when trying do so:
```
No 'registration_shared_secret' defined in config.
```
Looks like this is commented out and unused in the config currently.
https://github.com/dacruz21/matrix-chart/blob/master/templates/synapse/_homeserver.yaml#L871 

In the startup logs I'm also seeing:
```
Synapse requires that a list of trusted key servers are specified in order to
provide signing keys for other servers in the federation.
This homeserver does not have a trusted key server configured in
homeserver.yaml and will fall back to the default of 'matrix.org'.
Trusted key servers should be long-lived and stable which makes matrix.org a
good choice for many admins, but some admins may wish to choose another. To
suppress this warning, the admin should set 'trusted_key_servers' in
homeserver.yaml to their desired key server and 'suppress_key_server_warning'
to 'true'.
In a future release the software-defined default will be removed entirely and
the trusted key server will be defined exclusively by the value of
'trusted_key_servers'.
```
The last bit is the important part. 

This ones at https://github.com/dacruz21/matrix-chart/blob/master/templates/synapse/_homeserver.yaml#L1094 

And last but not least from startup logs:
```
Config is missing macaroon_secret_key
```
https://github.com/dacruz21/matrix-chart/blob/master/templates/synapse/_homeserver.yaml#L1030

**Comment by typokign** [comment]
Thanks again! I've published v1.4.0 with your changes, should be live in just a few minutes.
