### ISSUE TITLE
Liveness check may need to be desensitized a bit

### ISSUE THREAD

**Issue by Routhinator** [dacruz21/matrix-chart#30]
Now that I have my federation working thanks to the ingress improvements.. My container is crashlooping.. I couldn't figure out why at first but I realized that with all the work it's doing chatting with new federation partners the container is being killed by Kubernetes because it's not responsive enough:

```
  Warning  Unhealthy               22m (x4 over 23m)      kubelet, routhio-production-toronto-pool1-3u43e  Liveness probe failed: Get http://10.244.0.15:8008/_matrix/static/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

It might need to be given a failure allowance for these circumstances.

**Comment by typokign** [comment]
[Done](https://github.com/dacruz21/matrix-chart/commit/c9e55ec861da800ef84a4228027974b34313cc98)

Oof, didn't realize the default was 1 second. That's a bit too low for Synapse. I've upped it to 5 seconds, but you may want to raise it/lower it further.

**Comment by Routhinator** [comment]
Yeah, I have been watching this more and you may also want to add

```
failureThreshold: 3
```

I think when the server is in a burst of http traffic from federating it may be throttling incoming connections, which causes the connect timeout.  I'll try the update you made first though.

**Comment by typokign** [comment]
The default `failureThreshold` is already 3 (at least on minikube 1.18 where I'm testing right now). If your cloud provider has overriden it, feel free to change it back.

**Comment by typokign** [comment]
(Looks like it's also the official default in [the API spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#probe-v1-core))

**Comment by Routhinator** [comment]
Oh, derp. Sorry. That was right in front of my face on the docs too. :P

**Comment by Routhinator** [comment]
Stable without a restart for 12 minutes so far. I think that's got it - thanks.
