### ISSUE TITLE
Update homeserver.yaml from upstream

### ISSUE THREAD

**Issue by Routhinator** [dacruz21/matrix-chart#38]
Todo item as many of the config changes are backwards compatible for now, however the homeserver.yaml in the chart has drifted from upstream and a number of options that have been added are not there for reference for expanding on that config. Additionally we are using deprecated options, like `riot_base_url`

**Comment by typokign** [comment]
Thanks, merged the changes from upstream and added a few new config options to values.yaml. Also added `matrix.homeserverOverride` and `matrix.homeserverExtra` to override or extend the default config.
