### ISSUE TITLE
Github Pages Disabled?

### ISSUE THREAD

**Issue by jakesylvestre** [dacruz21/matrix-chart#54]
Hey - so I tried to install this chart and it appears the github pages is disable. Without modification, I forked it [here](https://xplorfin.github.io/matrix-chart/) and the readme shows up and the [chart works](https://xplorfin.github.io/matrix-chart/Chart.yaml).

I think you might need top trigger a re-render in the readme or something. This should also fix the missing readme on [artifact hub](https://artifacthub.io/packages/helm/dacruz21/matrix).

**Comment by jakesylvestre** [comment]
Hi,

It'd also appears the `exim-relay` image is missing:

```
 % docker pull devture/exim-relay:4.93.1-r0

Error response from daemon: manifest for devture/exim-relay:4.93.1-r0 not found: manifest unknown: manifest unknown
```

The manifest appears to be missing on all tags. I've opened up an issue about this in devture/exim-relay#4

**Comment by mgoerens** [comment]
https://github.com/dacruz21/matrix-chart/pull/56 should fix the `exim-relay` image, thanks for the workaround @jakesyl !

**Comment by jakesylvestre** [comment]
Thank you!

**Comment by mgoerens** [comment]
Well, it doesn't solve the Github pages issue though !
